[package]
name = "gitignore-in"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.20", features = ["blocking"] }

[dependencies.openssl]
# This is required for reqwest to work standalone
version = "0.10.57"
features = ["vendored"]
