// build .gitignore from .gitignore.in script

use crate::{
    format::{GENERATED_HEADER_LINES, SEPARATOR},
    gi::gi_command,
    gibo::gibo_command,
    script::{Comment, Echo, Gi, Gibo, GitIgnoreIn, GitIgnoreStatement, Invalid, Meaningless},
};

pub(crate) fn build(script: GitIgnoreIn) -> std::io::Result<String> {
    let mut result = String::new();
    for line in GENERATED_HEADER_LINES {
        result.push_str(line);
        result.push('\n');
    }
    let mut gibo_cache: std::collections::HashMap<String, String> =
        std::collections::HashMap::new();
    let mut gi_cache: std::collections::HashMap<String, String> = std::collections::HashMap::new();
    for statement in script.content {
        match statement {
            GitIgnoreStatement::Comment(Comment::Content(c)) => {
                result.push_str(&format!("# {c}\n"));
            }
            GitIgnoreStatement::Meaningless(Meaningless::Content(_m)) => {}
            GitIgnoreStatement::Gibo(Gibo::Target(target)) => {
                let content = if let Some(cached) = gibo_cache.get(&target) {
                    cached.clone()
                } else {
                    let fetched = gibo_command(&target)?;
                    gibo_cache.insert(target.clone(), fetched.clone());
                    fetched
                };
                result.push_str(&separator());
                result.push_str(&format!("# gibo dump {target}\n"));
                result.push_str(&content);
            }
            GitIgnoreStatement::Gi(Gi::Target(target)) => {
                let content = if let Some(cached) = gi_cache.get(&target) {
                    cached.clone()
                } else {
                    let fetched = gi_command(&target)?;
                    gi_cache.insert(target.clone(), fetched.clone());
                    fetched
                };
                result.push_str(&separator());
                result.push_str(&format!("# gi {target}\n"));
                result.push_str(&content);
            }
            GitIgnoreStatement::Echo(Echo::Content(echo)) => {
                if echo.starts_with("# gibo dump ") || echo.starts_with("# gi ") {
                    return Err(std::io::Error::other(format!(
                        "echo content {echo:?} starts with a reserved section header prefix; \
                         use a different prefix to avoid ambiguity during restore"
                    )));
                }
                result.push_str(&separator());
                result.push_str(&format!("{echo}\n"));
            }
            GitIgnoreStatement::Invalid(Invalid::Line { reason, .. }) => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    reason,
                ));
            }
        }
    }
    Ok(result)
}

fn separator() -> String {
    format!("{SEPARATOR}\n")
}

#[cfg(test)]
mod tests {
    use crate::parser::parse_text;

    use super::*;

    #[test]
    fn test_parse_text() {
        let text = r#"# comment
function meaningless() { echo "meaningless" }
gibo dump C++
gi C++
echo hello
"#;
        let result = parse_text(text);
        let result = build(result).unwrap();
        assert!(result.contains("# gi C++"));
        assert!(result.contains("# Created by https://www.toptal.com/developers/gitignore/api/C++"));
        assert!(
            result.contains("# Edit at https://www.toptal.com/developers/gitignore?templates=C++")
        );
        assert!(result.contains("# gibo dump C++"));
        assert!(result.contains("# Generated by gibo (https://github.com/simonwhitaker/gibo)"));
        assert!(result.contains("hello"));
    }

    #[test]
    fn generated_header_includes_official_site() {
        let result = build(GitIgnoreIn {
            content: Vec::new(),
        })
        .unwrap();
        assert!(result.contains("# See https://gitignore.in/"));
    }

    #[test]
    fn test_repeated_gi_target_dedup() {
        // Same target listed twice: build must succeed and emit both header lines,
        // producing identical content for each occurrence (cache hit on second call).
        let text = "gi C++\ngi C++\n";
        let script = parse_text(text);
        let result = build(script).unwrap();
        assert_eq!(result.matches("# gi C++").count(), 2);
    }

    #[test]
    fn test_repeated_gibo_target_dedup() {
        let text = "gibo dump C++\ngibo dump C++\n";
        let script = parse_text(text);
        let result = build(script).unwrap();
        assert_eq!(result.matches("# gibo dump C++").count(), 2);
    }

    #[test]
    fn test_echo_with_gibo_prefix_is_rejected() {
        let text = "echo '# gibo dump Rust'\n";
        let script = parse_text(text);
        let err = build(script).unwrap_err();
        assert!(err.to_string().contains("reserved section header prefix"));
    }

    #[test]
    fn test_echo_with_gi_prefix_is_rejected() {
        let text = "echo '# gi Rust'\n";
        let script = parse_text(text);
        let err = build(script).unwrap_err();
        assert!(err.to_string().contains("reserved section header prefix"));
    }

    #[test]
    fn test_multi_template_gibo_line_is_rejected() {
        let text = "gibo dump Rust macOS\n";
        let script = parse_text(text);
        let err = build(script).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidInput);
        assert!(err.to_string().contains("one template per line"));
    }

    #[test]
    fn test_multi_template_gi_line_is_rejected() {
        let text = "gi Rust macOS\n";
        let script = parse_text(text);
        let err = build(script).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidInput);
        assert!(err.to_string().contains("one template per line"));
    }
}
