pub(crate) const GENERATED_HEADER_LINES: [&str; 5] = [
    "# DO NOT EDIT THIS FILE",
    "# Generated by gitignore.in",
    "# See https://gitignore.in/",
    "# Edit .gitignore.in instead of this file",
    "# Run `gitignore.in` to build .gitignore",
];

/// Header lines from v0.2.0 and earlier, before "# See https://gitignore.in/" was added.
/// Used by `looks_generated` so that files generated by old binaries are still recognised.
pub(crate) const LEGACY_GENERATED_HEADER_LINES: [&str; 4] = [
    "# DO NOT EDIT THIS FILE",
    "# Generated by gitignore.in",
    "# Edit .gitignore.in instead of this file",
    "# Run `gitignore.in` to build .gitignore",
];

pub(crate) const SEPARATOR: &str =
    "# -----------------------------------------------------------------------------";
