pub(crate) const GENERATED_HEADER_LINES: [&str; 5] = [
    "# DO NOT EDIT THIS FILE",
    "# Generated by gitignore.in",
    "# See https://gitignore.in/",
    "# Edit .gitignore.in instead of this file",
    "# Run `gitignore.in` to build .gitignore",
];

pub(crate) const SEPARATOR: &str =
    "# -----------------------------------------------------------------------------";
