// Current .gitignore.in format version; increment on backward-incompatible format changes.
pub(crate) const GITIGNORE_IN_FORMAT_VERSION: &str = "v1";
pub(crate) const GITIGNORE_IN_FORMAT_PREFIX: &str = "# gitignore.in format: ";

/// Returns the `.gitignore.in` format version from `content`, or `None` for files
/// created before format versioning was introduced.
#[allow(dead_code)]
pub(crate) fn gitignore_in_format_version(content: &str) -> Option<&str> {
    content
        .lines()
        .find_map(|line| line.strip_prefix(GITIGNORE_IN_FORMAT_PREFIX))
}

pub(crate) const GENERATED_HEADER_LINES: [&str; 5] = [
    "# DO NOT EDIT THIS FILE",
    "# Generated by gitignore.in",
    "# See https://gitignore.in/",
    "# Edit .gitignore.in instead of this file",
    "# Run `gitignore.in` to build .gitignore",
];

/// Header lines from v0.2.0 and earlier, before "# See https://gitignore.in/" was added.
/// Used by `looks_generated` so that files generated by old binaries are still recognised.
pub(crate) const LEGACY_GENERATED_HEADER_LINES: [&str; 4] = [
    "# DO NOT EDIT THIS FILE",
    "# Generated by gitignore.in",
    "# Edit .gitignore.in instead of this file",
    "# Run `gitignore.in` to build .gitignore",
];

pub(crate) const SEPARATOR: &str =
    "# -----------------------------------------------------------------------------";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_format_version_in_header() {
        let content = "# See https://gitignore.in/\n# gitignore.in format: v1\ngibo dump Rust\n";
        assert_eq!(gitignore_in_format_version(content), Some("v1"));
    }

    #[test]
    fn returns_none_for_files_without_version_marker() {
        let content = "# See https://gitignore.in/\ngibo dump Rust\n";
        assert_eq!(gitignore_in_format_version(content), None);
    }

    #[test]
    fn current_version_matches_format_prefix_convention() {
        let marker = format!("{GITIGNORE_IN_FORMAT_PREFIX}{GITIGNORE_IN_FORMAT_VERSION}");
        assert_eq!(
            gitignore_in_format_version(&marker),
            Some(GITIGNORE_IN_FORMAT_VERSION)
        );
    }
}
