use std::process::ExitStatus;

fn validate_gibo_command_output(
    status: ExitStatus,
    stdout: String,
    stderr: &str,
    target: &str,
) -> std::io::Result<String> {
    if status.success() {
        if stdout.is_empty() {
            return Err(std::io::Error::other(format!(
                "Failed to get {target} from gibo: empty stdout (stderr={stderr})"
            )));
        }
        return Ok(stdout);
    }
    let code = status
        .code()
        .map(|c| c.to_string())
        .unwrap_or_else(|| "<signal>".to_string());
    Err(std::io::Error::other(format!(
        "Failed to get {target} from gibo: exit={code} stderr={stderr}"
    )))
}

fn validate_gibo_list_output(
    status: ExitStatus,
    stdout: String,
    stderr: &str,
) -> std::io::Result<Vec<String>> {
    if !status.success() {
        let code = status
            .code()
            .map(|c| c.to_string())
            .unwrap_or_else(|| "<signal>".to_string());
        return Err(std::io::Error::other(format!(
            "Failed to list templates from gibo: exit={code} stderr={stderr}"
        )));
    }
    Ok(stdout
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(ToString::to_string)
        .collect())
}

pub fn gibo_command(target: &str) -> std::io::Result<String> {
    let output = std::process::Command::new("gibo")
        .arg("dump")
        .arg(target)
        .output()?;

    let stdout = match String::from_utf8(output.stdout) {
        Ok(it) => it,
        Err(err) => return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, err)),
    };
    let stderr = match String::from_utf8(output.stderr) {
        Ok(it) => it,
        Err(err) => return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, err)),
    };
    validate_gibo_command_output(output.status, stdout, &stderr, target)
}

pub fn gibo_list() -> std::io::Result<Vec<String>> {
    let output = std::process::Command::new("gibo").arg("list").output()?;
    let stdout = match String::from_utf8(output.stdout) {
        Ok(it) => it,
        Err(err) => return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, err)),
    };
    let stderr = match String::from_utf8(output.stderr) {
        Ok(it) => it,
        Err(err) => return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, err)),
    };
    validate_gibo_list_output(output.status, stdout, &stderr)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::process::ExitStatusExt;

    fn make_status(code: i32) -> ExitStatus {
        // unix では exit code は (code << 8) で表現される。
        ExitStatus::from_raw(code << 8)
    }

    #[test]
    fn test_validate_gibo_command_output_ok() {
        let stdout = "### Generated by gibo ###\nfoo\n".to_string();
        let result =
            validate_gibo_command_output(make_status(0), stdout.clone(), "", "C++").unwrap();
        assert_eq!(result, stdout);
    }

    #[test]
    fn test_validate_gibo_command_output_rejects_non_zero_exit() {
        let err = validate_gibo_command_output(
            make_status(1),
            String::new(),
            "gibo: failed to clone repository",
            "C++",
        )
        .unwrap_err();
        assert!(err.to_string().contains("exit=1"));
        assert!(err.to_string().contains("failed to clone"));
    }

    #[test]
    fn test_validate_gibo_command_output_rejects_non_zero_with_stdout() {
        // exit 非ゼロでも部分的 stdout が出ているケース。garbage を
        // `.gitignore` に書き込まないように reject する。
        let err = validate_gibo_command_output(
            make_status(2),
            "partial output\n".to_string(),
            "boilerplate not found".to_string().as_str(),
            "C++",
        )
        .unwrap_err();
        assert!(err.to_string().contains("exit=2"));
    }

    #[test]
    fn test_validate_gibo_command_output_rejects_zero_exit_empty_stdout() {
        // exit 0 でも stdout が空なら空 `.gitignore` 書き込みを防ぐため reject。
        let err =
            validate_gibo_command_output(make_status(0), String::new(), "warn", "C++").unwrap_err();
        assert!(err.to_string().contains("empty stdout"));
    }

    #[test]
    fn test_validate_gibo_list_output_ok() {
        let stdout = "C++\nRust\nPython\n".to_string();
        let result = validate_gibo_list_output(make_status(0), stdout, "").unwrap();
        assert_eq!(result, vec!["C++", "Rust", "Python"]);
    }

    #[test]
    fn test_validate_gibo_list_output_rejects_non_zero_exit() {
        let err =
            validate_gibo_list_output(make_status(127), String::new(), "gibo: command failed")
                .unwrap_err();
        assert!(err.to_string().contains("exit=127"));
    }

    #[test]
    fn test_gibo_command() {
        let result = gibo_command("C++");
        let result = match result {
            Ok(result) => result,
            Err(e) => {
                eprintln!("{e}");
                unreachable!();
            }
        };
        assert!(result.contains("Generated by gibo"));
        assert!(result.contains("C++"));
    }

    #[test]
    fn test_gibo_command_fail() {
        let result = gibo_command("unknown-language");
        assert!(result.is_err());
    }
}
