use clap::{Parser, Subcommand};
use log::debug;
use std::{
    io::{ErrorKind, IsTerminal, Read, Write},
    path::Path,
    process::ExitCode,
};
mod assembler;
mod edit;
mod format;
mod gi;
mod gibo;
pub mod http_cache;
mod infer;
mod parser;
mod restore;
mod script;
mod shell;

const AFTER_HELP: &str =
    "Official site: https://gitignore.in/\nRepository: https://github.com/gitignore-in/gitignore-in";
const GITIGNORE_IN_HEADER_LINES: [&str; 2] = [
    "# See https://gitignore.in/",
    "# Edit this file and run `gitignore.in` to rebuild .gitignore",
];
const EXIT_GENERAL_ERROR: u8 = 1;
const EXIT_USAGE_ERROR: u8 = 2;
const EXIT_PERMISSION_DENIED: u8 = 13;
const EXIT_TEMPORARY_FAILURE: u8 = 75;
const MAX_FILE_BYTES: u64 = 1024 * 1024;

fn atomic_write(path: &Path, content: impl AsRef<[u8]>) -> std::io::Result<()> {
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let mut tmp = tempfile::NamedTempFile::new_in(dir)?;
    tmp.write_all(content.as_ref())?;
    tmp.persist(path).map_err(|e| e.error)?;
    Ok(())
}

fn main() -> ExitCode {
    env_logger::init();
    let cli = Cli::parse();
    run_cli(cli)
}

fn run_cli(cli: Cli) -> ExitCode {
    match run(cli) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("Error: {e}");
            ExitCode::from(exit_code_for_error(&e))
        }
    }
}

fn exit_code_for_error(e: &std::io::Error) -> u8 {
    match e.kind() {
        ErrorKind::InvalidInput | ErrorKind::AlreadyExists | ErrorKind::NotFound => {
            EXIT_USAGE_ERROR
        }
        ErrorKind::PermissionDenied => EXIT_PERMISSION_DENIED,
        ErrorKind::BrokenPipe
        | ErrorKind::ConnectionAborted
        | ErrorKind::ConnectionRefused
        | ErrorKind::ConnectionReset
        | ErrorKind::Interrupted
        | ErrorKind::NotConnected
        | ErrorKind::TimedOut
        | ErrorKind::UnexpectedEof => EXIT_TEMPORARY_FAILURE,
        _ => EXIT_GENERAL_ERROR,
    }
}

#[derive(Debug, Parser)]
#[command(
    name = "gitignore.in",
    version,
    about = "Manage .gitignore files with .gitignore.in",
    long_about = None,
    after_help = AFTER_HELP
)]
struct Cli {
    /// Suppress progress messages
    #[arg(long, global = true)]
    quiet: bool,
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Debug, Subcommand)]
enum Commands {
    /// Search templates available from gibo and gitignore.io.
    ///
    /// Omit queries to list every available template.
    Search {
        /// Search terms matched case-insensitively against template names.
        /// Omit to list every available template.
        queries: Vec<String>,
    },
    /// Add templates to .gitignore.in and rebuild .gitignore
    Add {
        /// Template names such as Rust, macOS, or node
        templates: Vec<String>,
    },
    /// Remove templates from .gitignore.in and rebuild .gitignore
    Remove {
        /// Template names such as Rust, macOS, or node
        templates: Vec<String>,
    },
    /// Restore .gitignore.in from a generated .gitignore and rebuild .gitignore
    Restore,
    /// Infer .gitignore.in from an existing .gitignore and rebuild .gitignore
    ///
    /// If the .gitignore was generated by gitignore.in and no explicit --gibo, --gi,
    /// or non-default --min-overlap is given, the file is restored directly without
    /// re-running inference. Providing --gibo, --gi, or a non-default --min-overlap
    /// bypasses this shortcut and always runs full inference.
    /// When both --gibo and --gi are omitted and the shortcut does not apply, all
    /// templates from both providers are checked (may trigger many network requests).
    ///
    /// Template scoring uses live catalog content fetched at run time. Results may
    /// differ between runs if provider catalogs have been updated since the last
    /// run. For reproducible gibo results, set GITIGNORE_IN_BOILERPLATES_REF to a
    /// fixed commit SHA before running infer.
    /// When only one of --gibo or --gi is provided, the other provider is not searched
    /// (its candidate list is treated as empty).
    Infer {
        /// Comma-separated gibo targets to consider
        #[arg(long, value_delimiter = ',')]
        gibo: Vec<String>,
        /// Comma-separated gitignore.io targets to consider
        #[arg(long, value_delimiter = ',')]
        gi: Vec<String>,
        /// Minimum number of matching lines required for a template
        #[arg(long, default_value_t = 2)]
        min_overlap: usize,
        /// Minimum percentage of a template's lines that must match
        #[arg(
            long,
            default_value_t = infer::DEFAULT_MIN_OVERLAP_PERCENT,
            value_parser = clap::value_parser!(u8).range(0..=100)
        )]
        min_overlap_percent: u8,
    },
}

fn pin_boilerplates_if_requested() -> std::io::Result<()> {
    // Stable public env-var API: callers in CI may rely on this across tool versions.
    const GITIGNORE_IN_BOILERPLATES_REF_ENV: &str = "GITIGNORE_IN_BOILERPLATES_REF";

    if let Ok(ref_spec) = std::env::var(GITIGNORE_IN_BOILERPLATES_REF_ENV) {
        if !ref_spec.is_empty() {
            gibo::pin_boilerplates(&ref_spec)?;
        }
    }
    Ok(())
}

fn run(cli: Cli) -> std::io::Result<()> {
    let progress = Progress::new(cli.quiet);
    match cli.command {
        Some(Commands::Search { queries }) => search_templates(queries),
        Some(Commands::Add { templates }) => {
            pin_boilerplates_if_requested()?;
            let updated = update_gitignore_in_file(UpdateMode::Add, templates, &progress)?;
            if updated > 0 {
                progress.message("Updated .gitignore.in");
            }
            build_gitignore(&progress)
        }
        Some(Commands::Remove { templates }) => {
            pin_boilerplates_if_requested()?;
            update_gitignore_in_file(UpdateMode::Remove, templates, &progress)?;
            progress.message("Updated .gitignore.in");
            build_gitignore(&progress)
        }
        Some(Commands::Restore) => {
            pin_boilerplates_if_requested()?;
            refuse_if_gitignore_in_exists("restore")?;
            restore_gitignore_in_file()?;
            progress.message("Restored .gitignore.in");
            build_gitignore(&progress)
        }
        Some(Commands::Infer {
            gibo,
            gi,
            min_overlap,
            min_overlap_percent,
        }) => {
            pin_boilerplates_if_requested()?;
            refuse_if_gitignore_in_exists("infer")?;
            let (new_in, seed) =
                compute_inferred_gitignore_in(gibo, gi, min_overlap, min_overlap_percent)?;
            atomic_write(Path::new(".gitignore.in"), &new_in)?;
            progress.message("Inferred .gitignore.in");
            build_gitignore_with_seed(seed, &progress)
        }
        None => {
            pin_boilerplates_if_requested()?;
            build_gitignore(&progress)
        }
    }
}

struct Progress {
    enabled: bool,
}

impl Progress {
    fn new(quiet: bool) -> Self {
        Self {
            enabled: !quiet && std::io::stderr().is_terminal(),
        }
    }

    fn message(&self, message: &str) {
        if self.enabled {
            eprintln!("{message}");
        }
    }
}

enum UpdateMode {
    Add,
    Remove,
}

fn build_gitignore(progress: &Progress) -> std::io::Result<()> {
    let started = std::time::Instant::now();
    match bootstrap_gitignore_in_file() {
        Ok(BootstrapStatus::AlreadyPresent) => {
            debug!("bootstrap: .gitignore.in already present");
        }
        Ok(BootstrapStatus::Initialized) => {
            progress.message("Initialized .gitignore.in");
            debug!("bootstrap: initialized .gitignore.in from template");
        }
        Ok(BootstrapStatus::Inferred) => {
            progress.message("Inferred .gitignore.in from .gitignore");
            debug!("bootstrap: inferred .gitignore.in from existing .gitignore");
        }
        Err(e) => {
            return Err(std::io::Error::new(
                e.kind(),
                format!("Failed to set up .gitignore.in: {e}"),
            ));
        }
    }
    let statements = parse_gitignore_in_file()?;
    debug!(
        "parsed {} statements from .gitignore.in",
        statements.content.len()
    );
    let result = assembler::build(statements)?;
    let path = Path::new(".gitignore");
    atomic_write(path, result)?;
    progress.message("Generated .gitignore");
    debug!(
        "build_gitignore complete ({:.0}ms)",
        started.elapsed().as_millis()
    );
    Ok(())
}

fn build_gitignore_with_seed(
    seed: assembler::TemplateCache,
    progress: &Progress,
) -> std::io::Result<()> {
    let started = std::time::Instant::now();
    match bootstrap_gitignore_in_file() {
        Ok(BootstrapStatus::AlreadyPresent) => {
            debug!("bootstrap: .gitignore.in already present");
        }
        Ok(BootstrapStatus::Initialized) => {
            progress.message("Initialized .gitignore.in");
            debug!("bootstrap: initialized .gitignore.in from template");
        }
        Ok(BootstrapStatus::Inferred) => {
            progress.message("Inferred .gitignore.in from .gitignore");
            debug!("bootstrap: inferred .gitignore.in from existing .gitignore");
        }
        Err(e) => {
            return Err(std::io::Error::new(
                e.kind(),
                format!("Failed to set up .gitignore.in: {e}"),
            ));
        }
    }
    let statements = parse_gitignore_in_file()?;
    debug!(
        "parsed {} statements from .gitignore.in",
        statements.content.len()
    );
    let result = assembler::build_with_seed(statements, seed)?;
    let path = Path::new(".gitignore");
    atomic_write(path, result)?;
    progress.message("Generated .gitignore");
    debug!(
        "build_gitignore_with_seed complete ({:.0}ms)",
        started.elapsed().as_millis()
    );
    Ok(())
}

fn search_templates(queries: Vec<String>) -> std::io::Result<()> {
    let catalog = edit::Catalog::load()?;
    let results = catalog.search(&queries);
    if results.is_empty() {
        let message = if queries.is_empty() {
            "No templates are available from gibo or gitignore.io".to_string()
        } else {
            format!("No templates matched: {}", queries.join(", "))
        };
        return Err(std::io::Error::other(message));
    }

    for template in results {
        println!(
            "{}\t{}",
            edit::provider_label(template.provider),
            template.target
        );
    }

    Ok(())
}

enum BootstrapStatus {
    AlreadyPresent,
    Initialized,
    Inferred,
}

fn bootstrap_gitignore_in_file() -> std::io::Result<BootstrapStatus> {
    let path = Path::new(".gitignore.in");
    if path.exists() {
        return Ok(BootstrapStatus::AlreadyPresent);
    }

    if Path::new(".gitignore").exists() {
        let (content, _) = compute_inferred_gitignore_in(
            Vec::new(),
            Vec::new(),
            2,
            infer::DEFAULT_MIN_OVERLAP_PERCENT,
        )?;
        atomic_write(path, content)?;
        return Ok(BootstrapStatus::Inferred);
    }

    atomic_write(path, gitignore_in_template_header())?;

    Ok(BootstrapStatus::Initialized)
}

fn refuse_if_gitignore_in_exists(command: &str) -> std::io::Result<()> {
    let path = Path::new(".gitignore.in");
    if path.exists() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::AlreadyExists,
            format!(
                ".gitignore.in already exists; remove it before running `gitignore.in {command}`"
            ),
        ));
    }
    Ok(())
}

const MAX_FILE_SIZE_DISPLAY: &str = "1 MiB";

fn restore_gitignore_in_file() -> std::io::Result<()> {
    let path = std::path::Path::new(".gitignore");
    let file = std::fs::File::open(path)?;
    let mut content = String::new();
    file.take(MAX_FILE_BYTES + 1).read_to_string(&mut content)?;
    if content.len() as u64 > MAX_FILE_BYTES {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            format!(
                ".gitignore exceeds size limit ({MAX_FILE_SIZE_DISPLAY} / {MAX_FILE_BYTES} bytes)"
            ),
        ));
    }
    let restored = add_gitignore_in_header(&restore::restore(&content));
    atomic_write(Path::new(".gitignore.in"), restored)?;
    Ok(())
}

fn compute_inferred_gitignore_in(
    gibo_targets: Vec<String>,
    gi_targets: Vec<String>,
    min_overlap: usize,
    min_overlap_percent: u8,
) -> std::io::Result<(String, assembler::TemplateCache)> {
    let path = std::path::Path::new(".gitignore");
    let file = std::fs::File::open(path)?;
    let mut content = String::new();
    file.take(MAX_FILE_BYTES + 1).read_to_string(&mut content)?;
    if content.len() as u64 > MAX_FILE_BYTES {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            format!(
                ".gitignore exceeds size limit ({MAX_FILE_SIZE_DISPLAY} / {MAX_FILE_BYTES} bytes)"
            ),
        ));
    }

    let (gibo_targets, gi_targets) = infer_target_selection(gibo_targets, gi_targets);
    let (inferred, cache) = infer::infer_with_cache(
        &content,
        &infer::InferOptions {
            gibo_targets,
            gi_targets,
            min_overlap,
            min_overlap_percent,
        },
    )?;
    Ok((add_gitignore_in_header(&inferred), cache))
}

fn infer_target_selection(
    gibo_targets: Vec<String>,
    gi_targets: Vec<String>,
) -> (infer::TemplateTargets, infer::TemplateTargets) {
    if gibo_targets.is_empty() && gi_targets.is_empty() {
        (infer::TemplateTargets::All, infer::TemplateTargets::All)
    } else {
        (
            infer::TemplateTargets::Explicit(gibo_targets),
            infer::TemplateTargets::Explicit(gi_targets),
        )
    }
}

fn update_gitignore_in_file(
    mode: UpdateMode,
    templates: Vec<String>,
    progress: &Progress,
) -> std::io::Result<usize> {
    if templates.is_empty() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "At least one template name is required",
        ));
    }

    match bootstrap_gitignore_in_file() {
        Ok(BootstrapStatus::Initialized) => {
            progress.message("Initialized .gitignore.in");
        }
        Ok(BootstrapStatus::Inferred) => {
            progress.message("Inferred .gitignore.in from .gitignore");
        }
        Ok(BootstrapStatus::AlreadyPresent) => {}
        Err(e) => return Err(e),
    }

    let line_ending = detect_gitignore_in_line_ending()?;
    let mut script = parse_gitignore_in_file()?;
    let invalid: Vec<String> = script
        .content
        .iter()
        .filter_map(|s| {
            if let script::GitIgnoreStatement::Invalid(script::Invalid::Line { content, reason }) =
                s
            {
                Some(format!("{content:?}: {reason}"))
            } else {
                None
            }
        })
        .collect();
    if !invalid.is_empty() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            format!(
                ".gitignore.in contains invalid line(s); fix or remove them before editing:\n{}",
                invalid.join("\n")
            ),
        ));
    }
    let changed = match mode {
        UpdateMode::Add => {
            let catalog = edit::Catalog::load()?;
            edit::add_templates(&mut script, &catalog, &templates)?.len()
        }
        UpdateMode::Remove => edit::remove_templates(&mut script, &templates)?.len(),
    };
    atomic_write(
        Path::new(".gitignore.in"),
        edit::render_with_line_ending(&script, line_ending),
    )?;
    Ok(changed)
}

fn detect_gitignore_in_line_ending() -> std::io::Result<edit::LineEnding> {
    let mut content = String::new();
    std::fs::File::open(".gitignore.in")?.read_to_string(&mut content)?;
    Ok(edit::LineEnding::detect(&content))
}

fn parse_gitignore_in_file() -> std::io::Result<script::GitIgnoreIn> {
    let path = std::path::Path::new(".gitignore.in");
    parse_path(path)
}

fn parse_path(path: &Path) -> std::io::Result<script::GitIgnoreIn> {
    let file = std::fs::File::open(path)?;
    let mut content = String::new();
    file.take(MAX_FILE_BYTES + 1).read_to_string(&mut content)?;
    if content.len() as u64 > MAX_FILE_BYTES {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            format!(
                "{} exceeds size limit ({MAX_FILE_SIZE_DISPLAY} / {MAX_FILE_BYTES} bytes)",
                path.display()
            ),
        ));
    }
    let result = parser::parse_text(&content);
    Ok(result)
}

fn gitignore_in_template_header() -> String {
    // Derive the format-version marker from the format-module constants instead of
    // hard-coding it here, so migration tooling and this header share one source of truth.
    format!(
        "{}\n{}{}\n{}\n",
        GITIGNORE_IN_HEADER_LINES[0],
        format::GITIGNORE_IN_FORMAT_PREFIX,
        format::GITIGNORE_IN_FORMAT_VERSION,
        GITIGNORE_IN_HEADER_LINES[1],
    )
}

fn add_gitignore_in_header(content: &str) -> String {
    let header = gitignore_in_template_header();
    if content.starts_with(&header) || content.starts_with(&GITIGNORE_IN_HEADER_LINES.join("\n")) {
        return content.to_string();
    }

    if content.is_empty() {
        return header;
    }

    format!("{header}\n{content}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Mutex, MutexGuard, OnceLock};
    use tempfile::TempDir;

    fn cwd_lock() -> &'static Mutex<()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
    }

    /// RAII guard that holds the cwd lock and restores the working directory on drop.
    /// Prevents cwd leaks and mutex poisoning when a test panics mid-assertion.
    struct CwdGuard {
        _lock: MutexGuard<'static, ()>,
        original_dir: std::path::PathBuf,
    }

    impl CwdGuard {
        fn new(temp_dir: &std::path::Path) -> Self {
            let lock = cwd_lock().lock().unwrap_or_else(|e| e.into_inner());
            let original_dir = std::env::current_dir().expect("failed to get current dir");
            std::env::set_current_dir(temp_dir).expect("failed to change current dir");
            CwdGuard {
                _lock: lock,
                original_dir,
            }
        }
    }

    impl Drop for CwdGuard {
        fn drop(&mut self) {
            let _ = std::env::set_current_dir(&self.original_dir);
        }
    }

    #[test]
    fn test_main() {
        let temp_dir = TempDir::new().expect("failed to create temp dir");
        let _guard = CwdGuard::new(temp_dir.path());
        let result = run(Cli {
            quiet: false,
            command: None,
        });
        assert!(result.is_ok());
        // check if the .gitignore.in file is in current directory
        let path = Path::new(".gitignore.in");
        assert!(path.exists());
        let content = std::fs::read_to_string(path).expect("failed to read .gitignore.in");
        assert!(content.contains("# See https://gitignore.in/"));

        // try again
        let result = run(Cli {
            quiet: false,
            command: None,
        });
        assert!(result.is_ok());
        assert!(path.exists());
    }

    #[test]
    fn test_bootstrap_infers_from_existing_gitignore() {
        let temp_dir = TempDir::new().expect("failed to create temp dir");
        let _guard = CwdGuard::new(temp_dir.path());
        std::fs::write(
            ".gitignore",
            "# DO NOT EDIT THIS FILE\n# Generated by gitignore.in\n# See https://gitignore.in/\n# Edit .gitignore.in instead of this file\n# Run `gitignore.in` to build .gitignore\n# -----------------------------------------------------------------------------\nplain-entry\n# -----------------------------------------------------------------------------\n!important.txt\n",
        )
        .expect("failed to write .gitignore");

        let result = run(Cli {
            quiet: false,
            command: None,
        });
        assert!(result.is_ok());

        let restored =
            std::fs::read_to_string(".gitignore.in").expect("failed to read .gitignore.in");
        assert_eq!(
            restored,
            "# See https://gitignore.in/\n# gitignore.in format: v1\n# Edit this file and run `gitignore.in` to rebuild .gitignore\n\necho 'plain-entry'\necho '!important.txt'\n"
        );
    }

    #[test]
    fn test_parse_restore_command() {
        let cli = Cli::parse_from(["gitignore.in", "restore"]);
        assert!(matches!(cli.command, Some(Commands::Restore)));
    }

    #[test]
    fn test_parse_add_command() {
        let cli = Cli::parse_from(["gitignore.in", "add", "Rust", "node"]);
        match cli.command {
            Some(Commands::Add { templates }) => {
                assert_eq!(templates, vec!["Rust".to_string(), "node".to_string()]);
            }
            _ => unreachable!(),
        }
    }

    #[test]
    fn test_parse_search_command() {
        let cli = Cli::parse_from(["gitignore.in", "search", "rust", "node"]);
        match cli.command {
            Some(Commands::Search { queries }) => {
                assert_eq!(queries, vec!["rust".to_string(), "node".to_string()]);
            }
            _ => unreachable!(),
        }
    }

    #[test]
    fn test_parse_remove_command() {
        let cli = Cli::parse_from(["gitignore.in", "remove", "Rust"]);
        match cli.command {
            Some(Commands::Remove { templates }) => {
                assert_eq!(templates, vec!["Rust".to_string()]);
            }
            _ => unreachable!(),
        }
    }

    #[test]
    fn test_parse_infer_command() {
        let cli = Cli::parse_from([
            "gitignore.in",
            "infer",
            "--gibo",
            "Rust,macOS",
            "--gi",
            "node",
            "--min-overlap",
            "3",
        ]);

        match cli.command {
            Some(Commands::Infer {
                gibo,
                gi,
                min_overlap,
                min_overlap_percent,
            }) => {
                assert_eq!(gibo, vec!["Rust".to_string(), "macOS".to_string()]);
                assert_eq!(gi, vec!["node".to_string()]);
                assert_eq!(min_overlap, 3);
                assert_eq!(min_overlap_percent, infer::DEFAULT_MIN_OVERLAP_PERCENT);
            }
            _ => unreachable!(),
        }
    }

    #[test]
    fn infer_targets_select_all_when_both_providers_are_omitted() {
        let (gibo_targets, gi_targets) = infer_target_selection(Vec::new(), Vec::new());

        assert_eq!(gibo_targets, infer::TemplateTargets::All);
        assert_eq!(gi_targets, infer::TemplateTargets::All);
    }

    #[test]
    fn infer_targets_keep_empty_provider_explicit_when_other_provider_is_set() {
        let (gibo_targets, gi_targets) =
            infer_target_selection(Vec::new(), vec!["node".to_string()]);

        assert_eq!(gibo_targets, infer::TemplateTargets::Explicit(Vec::new()));
        assert_eq!(
            gi_targets,
            infer::TemplateTargets::Explicit(vec!["node".to_string()])
        );
    }

    #[test]
    fn run_cli_maps_invalid_input_to_usage_exit_code() {
        let exit_code = run_cli(Cli {
            quiet: false,
            command: Some(Commands::Add {
                templates: Vec::new(),
            }),
        });

        assert_eq!(exit_code, ExitCode::from(EXIT_USAGE_ERROR));
    }

    #[test]
    fn exit_code_for_error_classifies_common_error_kinds() {
        assert_eq!(
            exit_code_for_error(&std::io::Error::new(ErrorKind::InvalidInput, "bad input")),
            EXIT_USAGE_ERROR
        );
        assert_eq!(
            exit_code_for_error(&std::io::Error::new(
                ErrorKind::PermissionDenied,
                "permission denied"
            )),
            EXIT_PERMISSION_DENIED
        );
        assert_eq!(
            exit_code_for_error(&std::io::Error::new(ErrorKind::TimedOut, "timeout")),
            EXIT_TEMPORARY_FAILURE
        );
        assert_eq!(
            exit_code_for_error(&std::io::Error::other("unexpected")),
            EXIT_GENERAL_ERROR
        );
    }

    #[test]
    fn add_gitignore_in_header_keeps_existing_header() {
        let content = "# See https://gitignore.in/\n# Edit this file and run `gitignore.in` to rebuild .gitignore\n";
        assert_eq!(add_gitignore_in_header(content), content);
    }

    #[test]
    fn parse_path_rejects_oversized_file() {
        let temp_dir = TempDir::new().expect("failed to create temp dir");
        let path = temp_dir.path().join("huge.in");
        let oversized = "x".repeat((MAX_FILE_BYTES + 1) as usize);
        std::fs::write(&path, oversized).expect("failed to write oversized file");
        let err = parse_path(&path).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidInput);
        assert!(err.to_string().contains("exceeds size limit"));
    }

    #[test]
    fn run_cli_maps_oversized_input_to_usage_exit_code() {
        let temp_dir = TempDir::new().expect("failed to create temp dir");
        let _guard = CwdGuard::new(temp_dir.path());
        let oversized = "x".repeat((MAX_FILE_BYTES + 1) as usize);
        std::fs::write(".gitignore.in", oversized).expect("failed to write .gitignore.in");
        let exit_code = run_cli(Cli {
            quiet: false,
            command: None,
        });
        assert_eq!(exit_code, ExitCode::from(EXIT_USAGE_ERROR));
    }

    #[test]
    fn restore_refuses_to_overwrite_existing_gitignore_in() {
        let temp_dir = TempDir::new().expect("failed to create temp dir");
        let _guard = CwdGuard::new(temp_dir.path());
        std::fs::write(".gitignore", "node_modules\n").expect("failed to write .gitignore");
        let original = "# hand-written\necho 'keep-me'\n";
        std::fs::write(".gitignore.in", original).expect("failed to write .gitignore.in");

        let result = run(Cli {
            quiet: false,
            command: Some(Commands::Restore),
        });

        assert!(result.is_err(), "restore should refuse to overwrite");
        let err = result.expect_err("restore should error");
        assert_eq!(err.kind(), std::io::ErrorKind::AlreadyExists);
        let preserved =
            std::fs::read_to_string(".gitignore.in").expect("failed to read .gitignore.in");
        assert_eq!(preserved, original);
    }

    #[test]
    fn restore_rebuilds_gitignore_after_writing_gitignore_in() {
        let temp_dir = TempDir::new().expect("failed to create temp dir");
        let _guard = CwdGuard::new(temp_dir.path());
        std::fs::write(
            ".gitignore",
            "# DO NOT EDIT THIS FILE\n# Generated by gitignore.in\n# See https://gitignore.in/\n# Edit .gitignore.in instead of this file\n# Run `gitignore.in` to build .gitignore\n# -----------------------------------------------------------------------------\nplain-entry\n",
        )
        .expect("failed to write .gitignore");

        let result = run(Cli {
            quiet: false,
            command: Some(Commands::Restore),
        });
        assert!(result.is_ok(), "restore should succeed: {result:?}");

        let restored =
            std::fs::read_to_string(".gitignore.in").expect("failed to read .gitignore.in");
        assert!(
            restored.contains("echo 'plain-entry'"),
            ".gitignore.in should be restored from .gitignore: {restored}"
        );

        let rebuilt = std::fs::read_to_string(".gitignore").expect("failed to read .gitignore");
        assert!(
            rebuilt.contains("# Generated by gitignore.in"),
            ".gitignore should be rebuilt with the generated header: {rebuilt}"
        );
        assert!(
            rebuilt.contains("plain-entry"),
            "rebuilt .gitignore should still contain the original entry: {rebuilt}"
        );
    }

    #[test]
    fn infer_rebuilds_gitignore_after_writing_gitignore_in() {
        let temp_dir = TempDir::new().expect("failed to create temp dir");
        let _guard = CwdGuard::new(temp_dir.path());
        // Generated-looking .gitignore so infer takes the no-network restore path.
        std::fs::write(
            ".gitignore",
            "# DO NOT EDIT THIS FILE\n# Generated by gitignore.in\n# See https://gitignore.in/\n# Edit .gitignore.in instead of this file\n# Run `gitignore.in` to build .gitignore\n# -----------------------------------------------------------------------------\nplain-entry\n",
        )
        .expect("failed to write .gitignore");

        let result = run(Cli {
            quiet: false,
            command: Some(Commands::Infer {
                gibo: Vec::new(),
                gi: Vec::new(),
                min_overlap: 2,
                min_overlap_percent: infer::DEFAULT_MIN_OVERLAP_PERCENT,
            }),
        });
        assert!(result.is_ok(), "infer should succeed: {result:?}");

        let inferred =
            std::fs::read_to_string(".gitignore.in").expect("failed to read .gitignore.in");
        assert!(
            inferred.contains("echo 'plain-entry'"),
            ".gitignore.in should be inferred from .gitignore: {inferred}"
        );

        let rebuilt = std::fs::read_to_string(".gitignore").expect("failed to read .gitignore");
        assert!(
            rebuilt.contains("# Generated by gitignore.in"),
            ".gitignore should be rebuilt with the generated header: {rebuilt}"
        );
        assert!(
            rebuilt.contains("plain-entry"),
            "rebuilt .gitignore should still contain the original entry: {rebuilt}"
        );
    }

    #[test]
    fn infer_refuses_to_overwrite_existing_gitignore_in() {
        let temp_dir = TempDir::new().expect("failed to create temp dir");
        let _guard = CwdGuard::new(temp_dir.path());
        std::fs::write(".gitignore", "node_modules\n").expect("failed to write .gitignore");
        let original = "# hand-written\necho 'keep-me'\n";
        std::fs::write(".gitignore.in", original).expect("failed to write .gitignore.in");

        let result = run(Cli {
            quiet: false,
            command: Some(Commands::Infer {
                gibo: Vec::new(),
                gi: Vec::new(),
                min_overlap: 2,
                min_overlap_percent: infer::DEFAULT_MIN_OVERLAP_PERCENT,
            }),
        });

        assert!(result.is_err(), "infer should refuse to overwrite");
        let err = result.expect_err("infer should error");
        assert_eq!(err.kind(), std::io::ErrorKind::AlreadyExists);
        let preserved =
            std::fs::read_to_string(".gitignore.in").expect("failed to read .gitignore.in");
        assert_eq!(preserved, original);
    }
}
