use crate::format::{
    GENERATED_HEADER_LINES as HEADER_LINES, LEGACY_GENERATED_HEADER_LINES, SEPARATOR,
};

pub(crate) fn restore(text: &str) -> String {
    let mut result = Vec::new();
    let mut lines = text.lines().peekable();

    while let Some(line) = lines.next() {
        if HEADER_LINES.contains(&line) {
            continue;
        }

        if line == SEPARATOR {
            let Some(section_head) = lines.next() else {
                break;
            };

            if let Some(target) = section_head.strip_prefix("# gibo dump ") {
                result.push(format!("gibo dump {}", shell_quote_target(target)));
                skip_generated_section(&mut lines);
                continue;
            }

            if let Some(target) = section_head.strip_prefix("# gi ") {
                result.push(format!("gi {}", shell_quote_target(target)));
                skip_generated_section(&mut lines);
                continue;
            }

            result.push(format!("echo {}", shell_quote(section_head)));

            continue;
        }

        if line.is_empty() {
            result.push(line.to_string());
            continue;
        }

        if let Some(comment) = restore_comment_line(line) {
            result.push(comment);
            continue;
        }

        result.push(format!("echo {}", shell_quote(line)));
    }

    result.join("\n") + "\n"
}

pub(crate) fn looks_generated(text: &str) -> bool {
    HEADER_LINES.iter().all(|line| text.contains(line))
        || LEGACY_GENERATED_HEADER_LINES
            .iter()
            .all(|line| text.contains(line))
}

fn skip_generated_section<'a, I>(lines: &mut std::iter::Peekable<I>)
where
    I: Iterator<Item = &'a str>,
{
    while let Some(next) = lines.peek() {
        if *next == SEPARATOR {
            break;
        }
        lines.next();
    }
}

// Decode the double-hash encoding that build() writes for comment lines.
// build() stores comments as `Comment::Content("# original")` and emits
// `# # original` (prefixing `# ` once more).  Stripping the outer `# `
// here recovers the original `# original` line from .gitignore.in.
fn restore_comment_line(line: &str) -> Option<String> {
    line.strip_prefix("# #")
        .map(|comment| format!("#{comment}"))
}

fn shell_quote_target(text: &str) -> String {
    if text.contains(|c: char| c.is_whitespace() || c == '\'') {
        shell_quote(text)
    } else {
        text.to_string()
    }
}

fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r#"'\''"#))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn legacy_four_line_header_is_recognized_as_generated() {
        // v0.2.0 generated files had 4 header lines (no "# See https://gitignore.in/").
        // looks_generated must return true so restore() is chosen over the heuristic infer path.
        let text = concat!(
            "# DO NOT EDIT THIS FILE\n",
            "# Generated by gitignore.in\n",
            "# Edit .gitignore.in instead of this file\n",
            "# Run `gitignore.in` to build .gitignore\n",
        );
        assert!(looks_generated(text));
    }

    #[test]
    fn restores_generated_gitignore() {
        let text = r#"# DO NOT EDIT THIS FILE
# Generated by gitignore.in
# See https://gitignore.in/
# Edit .gitignore.in instead of this file
# Run `gitignore.in` to build .gitignore
# # project comment
# -----------------------------------------------------------------------------
# gibo dump Linux
### Generated by gibo
foo
# -----------------------------------------------------------------------------
# gi Rust
### Created by gitignore.io
bar
# -----------------------------------------------------------------------------
!.env
"#;

        let expected = "# project comment\ngibo dump Linux\ngi Rust\necho '!.env'\n";
        assert_eq!(restore(text), expected);
    }

    #[test]
    fn quotes_echo_content() {
        let text = "# -----------------------------------------------------------------------------\na'b\n";
        assert_eq!(restore(text), "echo 'a'\\''b'\n");
    }

    #[test]
    fn restores_mixed_content_sections() {
        let text = r#"# DO NOT EDIT THIS FILE
# Generated by gitignore.in
# See https://gitignore.in/
# Edit .gitignore.in instead of this file
# Run `gitignore.in` to build .gitignore
# # keep this comment
# -----------------------------------------------------------------------------
plain-entry
# -----------------------------------------------------------------------------
!important.txt
# trailing note
"#;

        let expected =
            "# keep this comment\necho 'plain-entry'\necho '!important.txt'\necho '# trailing note'\n";
        assert_eq!(restore(text), expected);
    }

    #[test]
    fn round_trips_generated_comment_shape() {
        let restored = restore("# # original comment\n");
        assert_eq!(restored, "# original comment\n");
    }

    #[test]
    fn restores_empty_echo() {
        // separator + empty line comes from `echo ''` in .gitignore.in
        let text =
            "# -----------------------------------------------------------------------------\n\n";
        assert_eq!(restore(text), "echo ''\n");
    }

    #[test]
    fn quotes_multiword_gibo_target() {
        let text = concat!(
            "# DO NOT EDIT THIS FILE\n",
            "# Generated by gitignore.in\n",
            "# See https://gitignore.in/\n",
            "# Edit .gitignore.in instead of this file\n",
            "# Run `gitignore.in` to build .gitignore\n",
            "# -----------------------------------------------------------------------------\n",
            "# gibo dump Visual Studio\n",
            "### Generated by gibo\n",
            "foo\n",
            "# -----------------------------------------------------------------------------\n",
        );
        let restored = restore(text);
        assert_eq!(restored, "gibo dump 'Visual Studio'\n");
    }

    #[test]
    fn quotes_multiword_gi_target() {
        let text = concat!(
            "# DO NOT EDIT THIS FILE\n",
            "# Generated by gitignore.in\n",
            "# See https://gitignore.in/\n",
            "# Edit .gitignore.in instead of this file\n",
            "# Run `gitignore.in` to build .gitignore\n",
            "# -----------------------------------------------------------------------------\n",
            "# gi Visual Studio\n",
            "### Created by gitignore.io\n",
            "bar\n",
            "# -----------------------------------------------------------------------------\n",
        );
        let restored = restore(text);
        assert_eq!(restored, "gi 'Visual Studio'\n");
    }

    #[test]
    fn round_trips_empty_echo_via_build() {
        // build("echo ''\n") produces separator + empty line;
        // restore should recover "echo ''\n" from that output.
        use crate::build::build;
        use crate::parser::parse_text;
        let input = "echo ''\n";
        let script = parse_text(input);
        let built = build(script).unwrap();
        let restored = restore(&built);
        assert_eq!(restored, input);
    }
}
