name: Check Dependabot security updates

on:
  schedule:
    - cron: '0 0 * * 1'  # every Monday
  workflow_dispatch:

permissions:
  contents: read
  administration: read

jobs:
  check-dependabot-security-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Check Dependabot security updates
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./scripts/check-dependabot-security-updates.sh
