name: Check Dependabot security updates

on:
  schedule:
    - cron: '0 0 * * 1'  # every Monday
  workflow_dispatch:

permissions:
  contents: read
  administration: read

jobs:
  check-dependabot-security-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Check Dependabot security updates
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./scripts/check-dependabot-security-updates.sh
