name: octocov
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  octocov:
    runs-on: ubuntu-latest
    env:
      # For incremental builds
      CARGO_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        # For incremental builds
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          components: llvm-tools-preview

      # For incremental builds
      - name: git-restore-mtime
        uses: chetan/git-restore-mtime-action@d186aca54f8760da4dec55313195e51ed3ebb0b3 # v2.3

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: gitignore-in/install-gibo@9e7dba9e59f184b41f542669b0864687a6f69b45 # v0.1.0

      - name: coverage
        run: |
          cargo install cargo-llvm-cov || true  # when already cached
          cargo llvm-cov --lcov --output-path coverage.lcov

      # See also: https://github.com/k1LoW/octocov-action
      - name: Report coverage with octocov
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config: .octocov.yml
