name: Spellcheck
on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Check spelling
        uses: crate-ci/typos@bc212b92c93b7d2c8acb5fcb114250694513595b # master
        # typos is a Source code spell checker
        # https://github.com/crate-ci/typos
