name: Spellcheck
on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Check spelling
        uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # master
        # typos is a Source code spell checker
        # https://github.com/crate-ci/typos
