name: tests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - run: |
          wget https://github.com/simonwhitaker/gibo/releases/download/v3.0.7/gibo_Linux_x86_64.tar.gz
          tar -xzf gibo_Linux_x86_64.tar.gz
          cp gibo /usr/local/bin
          chmod +x /usr/local/bin/gibo
          gibo update

      - run: cargo test

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - run: |
          wget https://github.com/simonwhitaker/gibo/releases/download/v3.0.7/gibo_Linux_x86_64.tar.gz
          tar -xzf gibo_Linux_x86_64.tar.gz
          cp gibo /usr/local/bin
          chmod +x /usr/local/bin/gibo
          gibo update

      - run: |
          cargo install cargo-llvm-cov || true
          cargo llvm-cov --lcov --output-path coverage.lcov

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
